# Generated by Django 2.0.2 on 2018-08-05 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='subtitle',
            field=models.CharField(default='none', max_length=200, verbose_name='Subtítulo'),
        ),
        migrations.AddField(
            model_name='service',
            name='title',
            field=models.CharField(default='none', max_length=200, verbose_name='Título'),
        ),
    ]
