# Generated by Django 2.0.2 on 2018-08-05 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20180805_2026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='update',
            new_name='updated',
        ),
        migrations.AlterField(
            model_name='service',
            name='subtitle',
            field=models.CharField(default='', max_length=200, verbose_name='Subtítulo'),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(default='', max_length=200, verbose_name='Título'),
        ),
    ]
